name: Build
on:
  pull_request: 
    branches: [main]
    paths: ["**.bs"]
  push:
    branches: [main]
    paths: ["**.bs"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          DESTINATION: index.html
          SOURCE: spec.bs
          GH_PAGES_BRANCH: gh-pages
          BUILD_FAIL_ON: warning
